### ISSUE TITLE
Entity home power

### ISSUE THREAD

**Issue by alexsalvo1** [Rain1971/V2C_trydant#19]
Seria posible añadir una entidad "home power" ya que esta ya visible en la app?

**Comment by msanchezt** [comment]
Te refieres a: sensor.v2c_trydan_sensor_housepower?


![image](https://github.com/Rain1971/V2C_trydant/assets/6965401/446e36cf-e056-4e10-8971-9bbaefc0b0ce)

Ya está disponible. O no acabo de entender donde comentas de añadirla.

**Comment by alexsalvo1** [comment]
Perdona quería decir de la red eléctrica. No se porque escribí "home power".

En la app hay la diferencia entre lo generado de los paneles y los consumido da la casa.

No se si se puede lado integración o si me tengo que hacer el calculo yo en HA.

**Comment by Rain1971** [comment]
El sensor sensor.v2c_trydan_sensor_housepower se corresponde con el el valor que ves en la app de V2C. Si lo que quieres es saber cuanto de esto viene de la red electrica y cuanto viene del inversor FV tienes que hacer la operación aparte en el HA. En todo caso es algo que encaja mejor con la integración que tengas en HA de la fotovoltaica, no tanto con el cargador
