### ISSUE TITLE
Error en el calculo de las horas para Hoy?

### ISSUE THREAD

**Issue by msanchezt** [Rain1971/V2C_trydant#20]
Si lo estoy entiendiendo bien, parece que cuando le pasas un "Precio MAX para cargar" no muestra correctamente las horas "Hoy", sí que parece mostrar ocrrectamente las horas "Mañana". 

Aquí se ve como, siendo las 23:10h está mostrando "Hoy: 0", cuando debería mostrar "Hoy: 23"
En cambio las horas "Mañana" las muestra bien.
![11111](https://github.com/Rain1971/V2C_trydant/assets/6965401/325aa503-91a8-4ac0-96d1-18ab6b4f6e7d)

Aquí el detalle de todos los precios hora en éste ejemplo expuesto:

![2222](https://github.com/Rain1971/V2C_trydant/assets/6965401/45386ebb-1e67-4009-b535-86e8bdb0dbcd)

**Comment by msanchezt** [comment]
Ahora mismo son las 18.05h y lo que me extraña es que las 18 no aparece en "Hoy". Aparecen las 19 directamente. Puede ser que la hora en curso no se tenga en cuenta?

![image](https://github.com/Rain1971/V2C_trydant/assets/6965401/4158d7a9-fe23-4094-90f3-e049d6e1fbc6)

**Comment by Rain1971** [comment]
Nunca tiene en cuenta la hora actual para el cálculo de horas. Son horas completas de carga lo que responde el sistema

**Comment by msanchezt** [comment]
Entiendo. Lo planteaba desde la lógica de que para mi debería aparecer la hora en curso si cumple con el requisito de precio MAX a cargar, porque realmente el coche se pone a cargar a esa hora aunque no se muestre en "Horas carga"

En el ejemplo anterior: eran las 18h y el coche se puso a cargar porque la hora estaba a menos de 0.5€, sin embargo "18" no aparecía en las "Horas carga" y eso genera dudas y creo que hace que la lógica no se entienda bien.

No sé si le ves sentido a lo que digo o lo planteas distinto.

Gracias.

**Comment by Rain1971** [comment]
Desde mi punto de vista dado que no se si son las 18.00 o las 18.55 lo mejor es indicar siempre el peor de los casos, otro tema sería indicarlo en minutos o indicarlo en numero decimal. 

Lo que te marca la integración son las horas a las que se cargará un total de horas completas sin contar con la hora que no puedo partir, pero a la hora de indicar si a las 18h se cargará, si que lo marco porque a esa hora se carga, aunque sean 2 minutos.
