### ISSUE TITLE
sensor_chargeenergy last_reset not updated

### ISSUE THREAD

**Issue by kikediazfernandez** [Rain1971/V2C_trydant#23]
The last_reset attribute of sensor_chargenergy doesn't updates with each charge cycle and makes it unusable for energy panel, because after going to 0 statistics count it as negative. It should update last_reset with every reset to 0.
It shows:
state_class: total
last_reset: '2011-11-04T00:00:00'
unit_of_measurement: kWh
device_class: energy
friendly_name: V2C trydan Sensor ChargeEnergy

**Comment by Rain1971** [comment]
Hi and thanks this is crucial for ha, you are right. I will chage on the next version, it is simple to solve it

**Comment by kikediazfernandez** [comment]
Also added changes to restore state after restart, to avoid resetting charge by price setting when HA restarts
