### ISSUE TITLE
ChargePower and ChargeEnergy stuck at constant value after charging stopped

### ISSUE THREAD

**Issue by wanted156** [Rain1971/V2C_trydant#25]
Thanks for this integration!

I noticed that some values do not go to zero after charging is stopped, like ChargePower and ChargeEnergy. It remains constant on the value it was last. PV or HousePower are changing as expected.

![v2cChargePower](https://github.com/Rain1971/V2C_trydant/assets/19693647/8e19d068-7e98-4f8a-a3f9-579c7bdad891)

Using:
Home Assistant 2023.6.0
Frontend 20230607.0 - latest
Using integration v2.9.5

**Comment by Rain1971** [comment]
check the new version
