### ISSUE TITLE
Missing entities...wanted

### ISSUE THREAD

**Issue by bmss21** [Rain1971/V2C_trydant#28]
Since my wallbox was updated, I no longer have access to the 31 previously available entities and now only have access to 5 entities. I've tried everything, even going back to a previous HA installation where everything was functional, but I can't get more than these 5 entities.

Wallbox software version: 1.7.17
HA: Core                      2024.2.1
Supervisor                   2024.01.1
Operating System       11.5
Frontend                      20240207.1

![image](https://github.com/Rain1971/V2C_trydant/assets/118840001/c31bb91c-696c-4b44-9ba7-61d33e9676c3)
![image](https://github.com/Rain1971/V2C_trydant/assets/118840001/4ebf7129-70ec-44ef-84f6-7e6bdf124523)

**Comment by Rain1971** [comment]
Check your device what is sendind on https. Newer firmware versions have a bad json on response. Other topic is the wifi conection on trydan sometimes fail an need to restart, for this is nice to have the https answere you are gatting. Please post it here

**Comment by xkill** [comment]
In my case I have the following response to `GET /RealTimeData`:

```json
{
  "ID": "MyID123",
  "ChargeState": 1,
  "ReadyState": 1,
  "ChargePower": 0,
  "ChargeEnergy": 0,
  "SlaveError": 0,
  "ChargeTime": 2551,
  "HousePower": 363.03,
  "FVPower": 0,
  "BatteryPower": 0,
  "Paused": 0,
  "Locked": 0,
  "Timer": 0,
  "Intensity": 6,
  "Dynamic": 1,
  "MinIntensity": 6,
  "MaxIntensity": 32,
  "PauseDynamic": 0,
  "FirmwareVersion": "1.7.23",
  "DynamicPowerMode": 0,
  "ContractedPower": 5000
}
```
Do I have to query to other URI?


How can I configure the car battery and car consumption? There is no settings on the Integration page.

**Comment by Rain1971** [comment]
On the setup of the integration you can set the Kw/h of comsumtion of your car. That will tell the integration how to calculate Kw/h -> Km of charge. In my case, my car compsumption is 20.8Kw/h

![image](https://github.com/Rain1971/V2C_trydant/assets/61752351/c5044ee3-1765-48c9-b6ca-5dc86b338350)
