### ISSUE TITLE
Incidents reload

### ISSUE THREAD

**Issue by antonmpla** [Rain1971/V2C_trydant#32]
Hello, I am very happy with the application, but it gives me several incidents, I would like to know if it is possible to solve it and how?, and if not, I would like to consider it in future updates.
1-When I have the V2C data, the Huawei inverter stops sending me data for its application, and the V"C tells me Huawei error on the screen.
2-Many times I have to reload the V2C application, so that it gives me the data.
Thank you for the work done.

**Comment by Rain1971** [comment]
I'm not sure what is the real problem, if you prefer in spanish is ok for me.

1.- Your problem is with the V2C device against Huawei? As far as I understand you are telling problems with the device, isn't it?
2.- Wifi problems with the device?

**Comment by antonmpla** [comment]
Buenas, si el problema es V2C con Huawei-Dongle, están a una distancia de 5
metros.

Wifi. Primero sospeché que fueran problemas de cobertura con el wifi, pero
según mi router me dice que tienen muy buena cobertura y velocidad, tengo
dos routers en malla Nest wifi Pro, y me indica que los dos dispositivos se
conectan a 2,4GHz y que tienen una buena conexión. Además con el movil y
ordenador miro la conexión y es buena, claro que estos muy seguramente se
conectan a 5GHz.

Como he mencionado antes, cuando activo una app la otra se cuelga, Huawei
creo que se puede cablear, desconozco si lo permite el V2c (aparentemente
no veo conexión) en el interior hay un RJ45, pero tengo entendido que es
para la pinza amperimétrica. No tengo inconveniente en cablear los dos si
con esto lo soluciono.

He visto gente que se quejan de que el Huawei se colapsa cuando le pides
datos, no soy experto y acepto sugerencias.

Muchas Gracias

Adjunto fotos de V2C donde indica que el error es de Huawei, i del
grafico de datos del Huawei, donde se ven algunos puntos discontinuos en
valores observados, que tampoco ayuda.


Missatge de Rain1971 ***@***.***> del dia dv., 22 de març
2024 a les 12:54:

**Comment by Rain1971** [comment]
Buenas, No soy de V2C ni trabajo para ellos, así que mucho en el tema de las desconexiones no te puedo indicar. En mi caso el wifi de mi Trydan es tan inestable que opté por pasar de él y usar ese conector TJ45 que comentas ( intuyo que el problema del wifi es cosa del trydan porque mi punto de acceso está a 10m sin obstáculos y no tengo problemas de comunicación más que con el trydan, incluso mi controlador unifi me lo detecta como conectado pero pierde el ping, es decir que se mantiene la conexión pero se cuelga la comunicación por parte del trydan ). Si es para la pinza pero también es un modbus que te permite comunicar Modbus ( necesitas un conversor RJ45 a Ethernet ) con el Trydan. 

https://hub.docker.com/r/rsalasmatch/imagen_trydan

Este docker que publiqué ya hace tiempo se comunica con el trydan y genera una web compatible con la integración de home assistant. Es totalmente estable y desaparecen los problemas de comunicación del equipo, pero evidentemente no sirve para comunicar con el servidor de V2C, es una solución local.

No integré en este docker comunicación con inversores, más que con piza shelly y victron, a ver si tengo tiempo para retomarlo y lo hago.

Desconozco si hay algún firmware donde lo hayan solucionado el problema de comunicación, puedes intentar contactar con V2C y ver que te dicen ellos.

**Comment by antonmpla** [comment]
Gracias por la explicación.

Missatge de Rain1971 ***@***.***> del dia ds., 23 de març
2024 a les 8:16:
