### ISSUE TITLE
Pause forced by integration after upgrade

### ISSUE THREAD

**Issue by jammagan** [Rain1971/V2C_trydant#33]
After I upgraded to the latest version, charger pauses continously. Entity V2C trydan Switch Paused triggers by itself to enable so charge is paused just after some seconds I started the charge. No matther if I start the charge form V2C app or homeassistant, just a few seconds after pause is enabled and charge stops. I had to disable this entity to be able to charge the car, and now I have no control over the process.

**Comment by dacorde** [comment]
I confirm the same issue with last update to v2.9.7.
Even if it is locked, pause switch remains on, if you change to off, it is back to on in 14-21 seconds most of the times (there is not an exact pattern).

**Comment by Domy5** [comment]
same problem, it pauses only after a few seconds, not remembering that this pluing has been updated 5 days ago, I've been 2 days doing all kinds of tests because it didn't load.

**Comment by Rain1971** [comment]
So sorry I didn't check the file before commiting this version.

Issue solved on Version 2.9.8

**Comment by jammagan** [comment]
Amazing timing in solving it! Many thanks!!

**Comment by Domy5** [comment]
thanks for your work it's amazing
