### ISSUE TITLE
Only 6 entities after HA 2024.5.2 update

### ISSUE THREAD

**Issue by ElXaxe** [Rain1971/V2C_trydant#35]
Hi,

I've just update Home Assistant to 2024.5.2 version and V2C_trydant integration stopped working.

I uninstalled it and download it again. But now, only 6 entities appear. Any clues?
![image](https://github.com/Rain1971/V2C_trydant/assets/2937841/fa1127b8-3527-4cdd-90c0-4c6f94de8a36)
![image](https://github.com/Rain1971/V2C_trydant/assets/2937841/3cc93a48-7262-4b5c-a017-4843d7f67a20)

**Comment by Rain1971** [comment]
No he pasado por esa versión, siento no poder decirte mucho. Estoy en 2024.5.3 y funciona como siempre. Estas seguro de tener acceso a tu trydan? A veces pierde el wifi y eso hace que no comunique con la casa ni con el exterior.

**Comment by ElXaxe** [comment]
Hola,
He desinstalado por completo la integración y vuelto a instalar. Ya
funciona bien.
Mil gracias!

**Comment by ppnacho** [comment]
Hola, me pasa lo mismo con 2024.5.4, he instalado y solo salen 6 entidades, he eliminado y vuelto a instalar y sigue igual. Un detalle, al intentar poner el repositorio en HACS, me dice que ya esta instalado, por lo que lo instalo desde HACS sin poner nada en repositorios personalizados. La conectividad con el cargador esta OK, lo unico que no reporta todas las entidades

**Comment by ppnacho** [comment]
he puesto en un navegador la url http://IPdelCARGADOR/RealTimeData y si me reporta datos, 

{"ID":"IDdelCARGADOR","ChargeState":0,"ReadyState":0,"ChargePower":0.00,"ChargeEnergy":0.00,"SlaveError":0,"ChargeTime":0,"HousePower":464.00,"FVPower":4885.00,"BatteryPower":0.00,"Paused":0,"Locked":0,"Timer":0,"Intensity":0,"Dynamic":1,"MinIntensity":6,"MaxIntensity":20,"PauseDynamic":0,"FirmwareVersion":"2.1.7","DynamicPowerMode":2,"ContractedPower":4600}

no se por donde mirar, aparentemente tampoco me coge datos del sensor pvpc. Con la integracion nativa de HA si recibo hasta 14 entidades. A ver si me puedes ayudar. Version de firmware del cargador 2.1.7
