### ISSUE TITLE
Solo aparecen 6 entidades 2024.5.4

### ISSUE THREAD

**Issue by ppnacho** [Rain1971/V2C_trydant#36]
Hola, me pasa lo mismo con 2024.5.4, he instalado y solo salen 6 entidades, he eliminado y vuelto a instalar y sigue igual. Un detalle, al intentar poner el repositorio en HACS, me dice que ya esta instalado, por lo que lo instalo desde HACS sin poner nada en repositorios personalizados. La conectividad con el cargador esta OK, lo unico que no reporta todas las entidades

**Comment by ppnacho** [comment]
he puesto en un navegador la url http://ipdelcargador/RealTimeData y si me reporta datos,

{"ID":"IDdelCARGADOR","ChargeState":0,"ReadyState":0,"ChargePower":0.00,"ChargeEnergy":0.00,"SlaveError":0,"ChargeTime":0,"HousePower":464.00,"FVPower":4885.00,"BatteryPower":0.00,"Paused":0,"Locked":0,"Timer":0,"Intensity":0,"Dynamic":1,"MinIntensity":6,"MaxIntensity":20,"PauseDynamic":0,"FirmwareVersion":"2.1.7","DynamicPowerMode":2,"ContractedPower":4600}

no se por donde mirar, aparentemente tampoco me coge datos del sensor pvpc. Con la integracion nativa de HA si recibo hasta 14 entidades. A ver si me puedes ayudar. Version de firmware del cargador 2.1.7

**Comment by ppnacho** [comment]
La opción para cambiar la capacidad por defecto de la batería del vehículo no aparece al hacer la configuración

**Comment by mordecai0071** [comment]
Hola, a mi tampoco me aparece la capacidad de la batería al hacer la configuración.

**Comment by Rain1971** [comment]
![image](https://github.com/Rain1971/V2C_trydant/assets/61752351/1a5c79b8-fc62-487a-8a46-b9a970767636)
Debería apareceros esto así, que es lo que os aparece? Que version de home assistant? Yo lo he revisado con la 2024.6.3

**Comment by mordecai0071** [comment]
Si, así es como aparece. Mi comentario era porque en la doc de la
integración también hay un campo para la capacidad de la batería.
Saludos y enhorabuena

**Comment by Rain1971** [comment]
donde pone 20.8 son los Kwh a los 100Km que consume tu coche, si pones correcto este valor luego en el lovelance que te crees:

**Comment by mordecai0071** [comment]
Perfecto.
Gracias y enhorabuena oyes vez 👍
