### ISSUE TITLE
Question about cloud vs local

### ISSUE THREAD

**Issue by jcristovao** [Rain1971/V2C_trydant#37]
Hello,

This one is not so much an issue, but some questions to help me decide if I buy this charger or not :)

When you state
> This integration supports network connection to V2C trydan directly, so that take note of the V2C trydan static IP address previously.

Does this mean that we can connect directly to the charger using only local network?

Can the charger operate without the cloud in this mode / even if the internet connection is down?

Thank you very much

**Comment by Rain1971** [comment]
Yes, this is to connect localy only. You don't need internet. 

Wifi connection of trydan is not fully stable at least in my house. Some other people reported the same. You can use rs485 to ethernet if you have disconnections on wifi. I have also created a docker to emulate the comunication from rs485 to ethernet if you have problems

**Comment by wingmanx** [comment]
Hi.
I've just bought a V2C Trydan.
Installed HACS V2C_Trydan and it's all working. However, I have some issues regarding local network.
Blocked charger IP in the router, lost connection to charger in HA. Unblocked charger IP, connection to charger in HA returned.
Can you confirm that HACS V2C_Trydan works in local network only, without "phone home"?
This was the main reason for me to buy the V2C Trydan ...
Thanks.
