### ISSUE TITLE
Error Change Dynamic power mode Change

### ISSUE THREAD

**Issue by d4icon** [Rain1971/V2C_trydant#38]
Hola,

Me estoy encontrado con este error cuando intento cambiar el modo de control de potencia:

![imagen](https://github.com/Rain1971/V2C_trydant/assets/5176086/e752cfe3-9b5e-4081-807a-efb28be3cd27)

Alguna idea?

**Comment by Rain1971** [comment]
arreglado en la 2.9.10

**Comment by Polosaz** [comment]
Disculpad, a lo mejor es una pregunta muy simple, pero cómo se puede cambiar el Dynamic Power Mode? Pues en la documentación de la integración lo pone como entidad de sólo lectura no? Os agradecería cualquier ayuda en este sentido, para no depender sólo de la configuración de perfil de carga desde la app.

Sorry, maybe it's a very simple question, but how can I change the Dynamic Power Mode? In the integration documentation is referred as a read-only entity, right? I would appreciate any help in this regard, to not depend only on the charging profile configuration from the app.

**Comment by d4icon** [comment]
> Disculpad, a lo mejor es una pregunta muy simple, pero cómo se puede cambiar el Dynamic Power Mode? Pues en la documentación de la integración lo pone como entidad de sólo lectura no? Os agradecería cualquier ayuda en este sentido, para no depender sólo de la configuración de perfil de carga desde la app.
> 
> Sorry, maybe it's a very simple question, but how can I change the Dynamic Power Mode? In the integration documentation is referred as a read-only entity, right? I would appreciate any help in this regard, to not depend only on the charging profile configuration from the app.

Este sensor es un slider, que cambia el modo de carga dinamica, que es justo lo que se ha fixeado aqui:
![imagen](https://github.com/Rain1971/V2C_trydant/assets/5176086/e6ec1240-a8c9-464d-a1a7-12604d22b33d)

**Comment by Polosaz** [comment]
Ah, perfecto, muchas gracias. Aunque a mí esa entidad me sale como no modificable, sólo de información de estado. El slider que sí me sale modificable es v2c_dynamic_power_mode. Es así? Probaré a ver si moviendo el slider me cambia el modo sin problema. Gracias de nuevo.
<img width="407" alt="image" src="https://github.com/Rain1971/V2C_trydant/assets/129220485/328e5ae2-f1d2-4d30-9853-c8e4ead59bde">

<img width="404" alt="image" src="https://github.com/Rain1971/V2C_trydant/assets/129220485/7634b0d3-c924-42b7-b886-f6f137bd44f7">

**Comment by Polosaz** [comment]
Estoy viendo que a mí no me responde al movel el slider. Me salen los errores que poniáis arriba pese a que tengo la última versión de la integración.

Registrador: homeassistant.core
Fuente: core.py:2761
Ocurrió por primera vez: 07:28:52 (6 ocurrencias)
Último inicio de sesión: 16:49:03

Error executing service: <ServiceCall v2c_trydan.set_dynamic_power_mode_slider (c:01J1KT3VKDJNFAJWVH9BSF2ZM1): v2c_dynamic_power_mode=0.0>
Error executing service: <ServiceCall v2c_trydan.set_dynamic_power_mode_slider (c:01J1MSX28TREM60FR23BGJZ0M7): v2c_dynamic_power_mode=2.0>
Error executing service: <ServiceCall v2c_trydan.set_dynamic_power_mode_slider (c:01J1MSXGMMV0P2Z90MRTXJ80BX): v2c_dynamic_power_mode=6.0>
Error executing service: <ServiceCall v2c_trydan.set_dynamic_power_mode_slider (c:01J1MSXN357XS7D8YX6VG41MQC): v2c_dynamic_power_mode=5.0>
Error executing service: <ServiceCall v2c_trydan.set_dynamic_power_mode_slider (c:01J1MSXXNAT2GTXS43YSS405R4): v2c_dynamic_power_mode=0.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/v2c_trydan/__init__.py", line 116, in set_dynamic_power_mode_slider
    await async_set_dynamic_power_mode(hass, ip_address, dynamic_power_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_setup_entry.<locals>.async_set_dynamic_power_mode() takes 1 positional argument but 3 were given
