### ISSUE TITLE
No me crea ninguna entidad

### ISSUE THREAD

**Issue by Domy5** [Rain1971/V2C_trydant#8]
he instalado el complemento en HACS, y en integraciones puesta mi IP estática del V2C.

no sé qué mirar o como ponerlo en marcha

**Comment by Rain1971** [comment]
Crea un panel de home assistant. añade una tarjeta vacía con el contenido que ves en el ejemplo del https://github.com/Rain1971/V2C_trydant/blob/main/README.md

mira este ejemplo:

https://raw.githubusercontent.com/Rain1971/V2C_trydant/main/example.yaml

**Comment by Rain1971** [comment]
- que version de firmware tienes?
- Que versión de home assistant?

La manera en que dialoga es muy simple. Para ver si funciona abre un navegador y pon http://192.168.1.160/RealTimeData

Te tiene que retornar los datos, si no ves nada es que o no tienes conexión con ese equipo o tienes una versión del firmware antigua.

El firmware de ha también puede ser importante dado que ha ido sufriendo varios cambios, en las versiones de este año no te debería de dar ningún problema.

Ya me cuentas

**Comment by Domy5** [comment]
Solucionado¡¡ gracias a la URL que he podido ir comprobando otras cosas, efectivamente no llegaba información, el problema fue por una directiva de mi red wifi (políticas de invitados), nada que ver con el componente que funciona perfectamente.

muchas gracias por el soporte.

un saludo
